/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication3;

import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author User
 */
public final class ADDEL extends javax.swing.JFrame {

    /**
     * Creates new form ADDEL
     */
    public ADDEL() {
        initComponents();
        show_user();
        ((JTextField)dob.getDateEditor().getUiComponent()).setEditable(false);
    }
    
    /**
     *
     * @return
     */
    public ArrayList<User> userList()
    {
        ArrayList<User> usersList = new ArrayList<>();
        try
        {
             Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/student","root","");
            String query1="SELECT * FROM stdreg";
            Statement st = con.createStatement();
            
            ResultSet rs = st.executeQuery(query1);
            User user;
            while(rs.next())
            {
                user = new User(rs.getString("sname"),rs.getString("password"),rs.getInt("stdid"),rs.getString("mname"),rs.getString("fname"),rs.getString("gender"),rs.getString("dob"),rs.getString("email"),rs.getString("clname"),rs.getInt("degagg"),rs.getInt("degpass"),rs.getInt("sslcperc"),rs.getInt("sslcpass"),rs.getInt("pucperc"),rs.getInt("pucpass"),rs.getInt("backlogs"));
                usersList.add(user);
            }
            
        }
        catch(ClassNotFoundException | SQLException e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        return usersList;
    }
    public void show_user()
    {
        ArrayList<User> list = userList();
        DefaultTableModel model = (DefaultTableModel) jTable_Display_User.getModel();
        Object[] row = new Object[0x10];
        for(int i=0;i<list.size();i++)
        {
             row[0]=list.get(i).getsname();
             row[1]=list.get(i).getpassword();
             row[2]=list.get(i).getstdid();
             row[3]=list.get(i).getmname();
             row[4]=list.get(i).getfname();
             row[5]=list.get(i).getgender();
             row[6]=list.get(i).getdob();
             row[7]=list.get(i).getemail();
             row[8]=list.get(i).getclname();
             row[9]=list.get(i).getdegagg();
             row[10]=list.get(i).getdegpass();
             row[11]=list.get(i).getsslcperc();
             row[12]=list.get(i).getsslcpass();
             row[13]=list.get(i).getpucperc();
             row[14]=list.get(i).getpucpass();
             row[15]=list.get(i).getbacklogs();
             model.addRow(row);
            
        }
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_Display_User = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        mname = new javax.swing.JTextField();
        fname = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        email = new javax.swing.JTextField();
        clname = new javax.swing.JTextField();
        degagg = new javax.swing.JTextField();
        degpass = new javax.swing.JTextField();
        sslcperc = new javax.swing.JTextField();
        sslcpass = new javax.swing.JTextField();
        pucperc = new javax.swing.JTextField();
        pucpass = new javax.swing.JTextField();
        backlogs = new javax.swing.JTextField();
        password = new javax.swing.JTextField();
        dob = new com.toedter.calendar.JDateChooser();
        stdid = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        sname1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton2.setForeground(new java.awt.Color(51, 51, 255));
        jButton2.setText("DELETE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("ALL STUDENTS INFORMATION");

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jTable_Display_User.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jTable_Display_User.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable_Display_User.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Password", "ID", "Mother Name", "Father Name", "gender", "dob", "email", "clname", "degagg", "degpass", "sslcperc", "sslcpass", "pucperc", "pucpass", "backlogs"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_Display_User.setMaximumSize(new java.awt.Dimension(3000, 0));
        jTable_Display_User.setSelectionBackground(new java.awt.Color(51, 255, 0));
        jTable_Display_User.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_Display_UserMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable_Display_User);
        if (jTable_Display_User.getColumnModel().getColumnCount() > 0) {
            jTable_Display_User.getColumnModel().getColumn(0).setPreferredWidth(80);
            jTable_Display_User.getColumnModel().getColumn(3).setPreferredWidth(100);
            jTable_Display_User.getColumnModel().getColumn(4).setResizable(false);
            jTable_Display_User.getColumnModel().getColumn(4).setPreferredWidth(100);
            jTable_Display_User.getColumnModel().getColumn(6).setPreferredWidth(80);
            jTable_Display_User.getColumnModel().getColumn(7).setPreferredWidth(100);
            jTable_Display_User.getColumnModel().getColumn(8).setPreferredWidth(100);
        }

        jButton3.setForeground(new java.awt.Color(51, 51, 255));
        jButton3.setText("<< BACK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication3/icons8-home-48.png"))); // NOI18N
        jLabel21.setText("jLabel5");
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3)
                .addGap(574, 574, 574)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(602, 602, 602)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 410, Short.MAX_VALUE)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jScrollPane2)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("STUDENT NAME");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, 34));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("PASSWORD");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 113, 28));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("STUDENT ID");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 113, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("MOTHER NAME");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 113, 38));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("FATHER NAME");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, 113, 35));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("GENDER");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 93, 113, 20));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("DOB");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, 113, 27));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("EMAIL ID");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, 113, 32));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("COLLEGE NAME");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 50, 113, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("DEGREE AGGREGATE");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 90, 150, 32));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("PASS YEAR GRADUATION");
        jLabel13.setToolTipText("PASS");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 130, 185, 27));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("10TH PERCENTAGE");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 170, 185, 26));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("PASS YEAR SSLC");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 50, 130, 32));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("12TH PERCENTAGE");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 90, 140, 27));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("PASS YEAR PUC");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 130, 120, 20));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("BACKLOGS");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 170, 90, -1));

        mname.setEditable(false);
        mname.setBackground(new java.awt.Color(153, 153, 153));
        mname.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        mname.setForeground(new java.awt.Color(255, 255, 255));
        mname.setToolTipText("ENTER THE MOTHER NAME");
        mname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                mnameKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mnameKeyTyped(evt);
            }
        });
        jPanel2.add(mname, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 170, 28));

        fname.setEditable(false);
        fname.setBackground(new java.awt.Color(153, 153, 153));
        fname.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        fname.setForeground(new java.awt.Color(255, 255, 255));
        fname.setToolTipText("ENTER THE FATHER NAME");
        fname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fnameKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fnameKeyTyped(evt);
            }
        });
        jPanel2.add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 50, 170, 29));

        jRadioButton1.setBackground(new java.awt.Color(153, 153, 153));
        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("MALE");
        jPanel2.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, -1, -1));

        jRadioButton2.setBackground(new java.awt.Color(153, 153, 153));
        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText("FEMALE");
        jPanel2.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 90, -1, -1));

        email.setEditable(false);
        email.setBackground(new java.awt.Color(153, 153, 153));
        email.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        email.setForeground(new java.awt.Color(255, 255, 255));
        email.setToolTipText("ENTER THE EMAIL ID");
        jPanel2.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 170, 170, 31));

        clname.setEditable(false);
        clname.setBackground(new java.awt.Color(153, 153, 153));
        clname.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        clname.setForeground(new java.awt.Color(255, 255, 255));
        clname.setToolTipText("ENTER THE COLLAGE NAME");
        clname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                clnameKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                clnameKeyTyped(evt);
            }
        });
        jPanel2.add(clname, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 50, 170, 30));

        degagg.setEditable(false);
        degagg.setBackground(new java.awt.Color(153, 153, 153));
        degagg.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        degagg.setForeground(new java.awt.Color(255, 255, 255));
        degagg.setToolTipText("ENTER THE DEGREE AGGRIGATE");
        degagg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                degaggKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                degaggKeyTyped(evt);
            }
        });
        jPanel2.add(degagg, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 90, 170, 29));

        degpass.setEditable(false);
        degpass.setBackground(new java.awt.Color(153, 153, 153));
        degpass.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        degpass.setForeground(new java.awt.Color(255, 255, 255));
        degpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                degpassActionPerformed(evt);
            }
        });
        degpass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                degpassKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                degpassKeyTyped(evt);
            }
        });
        jPanel2.add(degpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 130, 170, 30));

        sslcperc.setEditable(false);
        sslcperc.setBackground(new java.awt.Color(153, 153, 153));
        sslcperc.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        sslcperc.setForeground(new java.awt.Color(255, 255, 255));
        sslcperc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                sslcpercKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                sslcpercKeyTyped(evt);
            }
        });
        jPanel2.add(sslcperc, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 170, 170, 30));

        sslcpass.setEditable(false);
        sslcpass.setBackground(new java.awt.Color(153, 153, 153));
        sslcpass.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        sslcpass.setForeground(new java.awt.Color(255, 255, 255));
        sslcpass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                sslcpassKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                sslcpassKeyTyped(evt);
            }
        });
        jPanel2.add(sslcpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 50, 110, 30));

        pucperc.setEditable(false);
        pucperc.setBackground(new java.awt.Color(153, 153, 153));
        pucperc.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        pucperc.setForeground(new java.awt.Color(255, 255, 255));
        pucperc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pucpercKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pucpercKeyTyped(evt);
            }
        });
        jPanel2.add(pucperc, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 90, 110, 32));

        pucpass.setEditable(false);
        pucpass.setBackground(new java.awt.Color(153, 153, 153));
        pucpass.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        pucpass.setForeground(new java.awt.Color(255, 255, 255));
        pucpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pucpassActionPerformed(evt);
            }
        });
        pucpass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pucpassKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pucpassKeyTyped(evt);
            }
        });
        jPanel2.add(pucpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 130, 110, 32));

        backlogs.setEditable(false);
        backlogs.setBackground(new java.awt.Color(153, 153, 153));
        backlogs.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        backlogs.setForeground(new java.awt.Color(255, 255, 255));
        backlogs.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                backlogsKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                backlogsKeyTyped(evt);
            }
        });
        jPanel2.add(backlogs, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 170, 110, 30));

        password.setEditable(false);
        password.setBackground(new java.awt.Color(153, 153, 153));
        password.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        password.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 170, 30));

        dob.setBackground(new java.awt.Color(153, 153, 153));
        dob.setDateFormatString("yyyy-MM-d");
        jPanel2.add(dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 130, 170, 27));

        stdid.setEditable(false);
        stdid.setBackground(new java.awt.Color(153, 153, 153));
        stdid.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        stdid.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(stdid, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 170, 30));

        jPanel3.setBackground(new java.awt.Color(0, 204, 0));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("STUDENT INFORMATION");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(628, Short.MAX_VALUE)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(523, 523, 523))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1340, 40));

        sname1.setEditable(false);
        sname1.setBackground(new java.awt.Color(153, 153, 153));
        sname1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        sname1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(sname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 170, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        NewJFrame17 hh  = new NewJFrame17();
        hh.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        DEL DL=new DEL();
        DL.setVisible(true);
      
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void mnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mnameKeyPressed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_mnameKeyPressed

    private void mnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mnameKeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_mnameKeyTyped

    private void fnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fnameKeyPressed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_fnameKeyPressed

    private void fnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fnameKeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_fnameKeyTyped

    private void clnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_clnameKeyPressed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_clnameKeyPressed

    private void clnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_clnameKeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_clnameKeyTyped

    private void degaggKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_degaggKeyPressed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_degaggKeyPressed

    private void degaggKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_degaggKeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_degaggKeyTyped

    private void degpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_degpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_degpassActionPerformed

    private void degpassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_degpassKeyPressed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_degpassKeyPressed

    private void degpassKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_degpassKeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_degpassKeyTyped

    private void sslcpercKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sslcpercKeyPressed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_sslcpercKeyPressed

    private void sslcpercKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sslcpercKeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_sslcpercKeyTyped

    private void sslcpassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sslcpassKeyPressed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_sslcpassKeyPressed

    private void sslcpassKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sslcpassKeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_sslcpassKeyTyped

    private void pucpercKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pucpercKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_pucpercKeyPressed

    private void pucpercKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pucpercKeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_pucpercKeyTyped

    private void pucpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pucpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pucpassActionPerformed

    private void pucpassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pucpassKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_pucpassKeyPressed

    private void pucpassKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pucpassKeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_pucpassKeyTyped

    private void backlogsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_backlogsKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_backlogsKeyPressed

    private void backlogsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_backlogsKeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_backlogsKeyTyped

    private void jTable_Display_UserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_Display_UserMouseClicked
        // TODO add your handling code here:
         DefaultTableModel model = (DefaultTableModel) jTable_Display_User.getModel();
        int selectedIndex = jTable_Display_User.getSelectedRow();
        String stdID = model.getValueAt(selectedIndex,2).toString();
        try
        {
            
          
                Class.forName("com.mysql.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/student","root","");
                String sql;
                PreparedStatement pst;
           
                sql = "SELECT *FROM `stdreg` WHERE stdid = ? LIMIT 0 , 30";
                pst = con.prepareStatement(sql);
                pst.setString(1,stdID);
                ResultSet rs=pst.executeQuery();
                
                if(rs.next())
                {    
                       String snam = rs.getString(1);
                      
                       String passwor =rs.getString(2);
                       String stdi = rs.getString(3);
                       String mnam = rs.getString(4);
                       String fnam = rs.getString(5);
                       String gende = rs.getString(6);
                       
                       String dobr = rs.getString(7);
                      ((JTextField)dob.getDateEditor().getUiComponent()).setText(dobr);

                       String emai = rs.getString(8);
                       String clnam = rs.getString(9);
                       String degag = rs.getString(10);
                       String degpas = rs.getString(11);
                       String sslcper = rs.getString(12);
                       String sslcpas = rs.getString(13);
                       String pucper = rs.getString(14);
                       String pucpas = rs.getString(15);
                       String backlog = rs.getString(16);
                  
                       sname1.setText(snam);
                        password.setText(passwor);
                        stdid.setText(stdi);
                        mname.setText(mnam);
                        fname.setText(fnam);
                        String a="MALE";
                        String b="FEMALE";
                        if(gende.equals(a))
                        {
                            jRadioButton2.setSelected(false);
                            jRadioButton1.setSelected(true);
                        }
                        if(gende.equals(b))
                        {
                           jRadioButton1.setSelected(false);
                            jRadioButton2.setSelected(true);
                        }
                        email.setText(emai);
                        clname.setText(clnam);
                        degagg.setText(degag);
                        degpass.setText(degpas);
                        sslcperc.setText(sslcper);
                        sslcpass.setText(sslcpas);
                        pucperc.setText(pucper);
                        pucpass.setText(pucpas);
                        backlogs.setText(backlog);
                        
                }
        }
         catch(HeadlessException | ClassNotFoundException | SQLException e)
        {
                JOptionPane.showMessageDialog(null,e);
        }

    }//GEN-LAST:event_jTable_Display_UserMouseClicked

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jLabel21MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ADDEL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ADDEL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ADDEL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ADDEL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ADDEL().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField backlogs;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField clname;
    private javax.swing.JTextField degagg;
    private javax.swing.JTextField degpass;
    private com.toedter.calendar.JDateChooser dob;
    private javax.swing.JTextField email;
    private javax.swing.JTextField fname;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable_Display_User;
    private javax.swing.JTextField mname;
    private javax.swing.JTextField password;
    private javax.swing.JTextField pucpass;
    private javax.swing.JTextField pucperc;
    private javax.swing.JTextField sname1;
    private javax.swing.JTextField sslcpass;
    private javax.swing.JTextField sslcperc;
    private javax.swing.JTextField stdid;
    // End of variables declaration//GEN-END:variables
}
