/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication3;

import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class CRITERIA extends javax.swing.JFrame {
           
    /**
     * Creates new form CRITERIA
     */
    public CRITERIA() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        sslcperc = new javax.swing.JTextField();
        pucperc = new javax.swing.JTextField();
        degagg = new javax.swing.JTextField();
        backlogs = new javax.swing.JTextField();
        degpass = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel15 = new javax.swing.JLabel();
        YEAR = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        comp_ID = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        comp_descr = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(230, 0));

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("10th Aggregate");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 150, 43));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("12th Aggregate");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 160, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Graduation aggregate");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 210, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Backlogs");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, 160, 32));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Passing year of degree");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 240, 40));

        sslcperc.setBackground(new java.awt.Color(153, 153, 153));
        sslcperc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 153)));
        sslcperc.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                sslcpercMouseMoved(evt);
            }
        });
        sslcperc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sslcpercMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sslcpercMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                sslcpercMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                sslcpercMouseReleased(evt);
            }
        });
        sslcperc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                sslcpercKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                sslcpercKeyTyped(evt);
            }
        });
        jPanel1.add(sslcperc, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, 112, 30));

        pucperc.setBackground(new java.awt.Color(153, 153, 153));
        pucperc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 153)));
        pucperc.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        pucperc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pucpercMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pucpercMouseExited(evt);
            }
        });
        pucperc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pucpercKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pucpercKeyTyped(evt);
            }
        });
        jPanel1.add(pucperc, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, 112, 30));

        degagg.setBackground(new java.awt.Color(153, 153, 153));
        degagg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 153)));
        degagg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                degaggMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                degaggMouseExited(evt);
            }
        });
        degagg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                degaggKeyTyped(evt);
            }
        });
        jPanel1.add(degagg, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, 112, 30));

        backlogs.setBackground(new java.awt.Color(153, 153, 153));
        backlogs.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 153)));
        backlogs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backlogsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backlogsMouseExited(evt);
            }
        });
        backlogs.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                backlogsKeyTyped(evt);
            }
        });
        jPanel1.add(backlogs, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 360, 112, 30));

        degpass.setBackground(new java.awt.Color(153, 153, 153));
        degpass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 153)));
        degpass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                degpassMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                degpassMouseExited(evt);
            }
        });
        degpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                degpassActionPerformed(evt);
            }
        });
        degpass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                degpassKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                degpassKeyTyped(evt);
            }
        });
        jPanel1.add(degpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 320, 112, 30));

        jButton1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton1.setText("SUBMIT");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 580, 120, 30));

        jButton2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton2.setText("CLEAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 580, 120, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 0, 0));
        jLabel7.setText(">=");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, -1, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 0, 0));
        jLabel8.setText(">=");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, -1, 36));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 0, 0));
        jLabel9.setText(">=");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, 40, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 0, 0));
        jLabel10.setText("=");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 320, 20, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 0, 0));
        jLabel11.setText("<=");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 360, -1, 30));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("Select the Company name");

        jList1.setBackground(new java.awt.Color(204, 204, 204));
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "WIPRO", "INFOSYS", "TCS", "DELOITTE", "COGNIZANT", "CONCENTRIX", "MICROSOFT", "OTHER" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 51));
        jLabel15.setText("YEAR");

        YEAR.setBackground(new java.awt.Color(153, 153, 153));
        YEAR.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        YEAR.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                YEARKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                YEARKeyReleased(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 0));
        jLabel16.setText("ID");

        comp_ID.setBackground(new java.awt.Color(153, 153, 153));
        comp_ID.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        comp_ID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                comp_IDKeyPressed(evt);
            }
        });

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("yyyy Format");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLabel15)
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(YEAR, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comp_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel18))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(YEAR, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)
                            .addComponent(comp_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 770, 90));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 51, 51));
        jLabel13.setText("ADD DETAILS");
        jLabel13.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 280, 40));

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(153, 153, 153));
        jTextField1.setToolTipText("Specify the company");
        jTextField1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        jTextField1.setDoubleBuffered(true);
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 0));
        jLabel14.setText("If Other company? Specify it.");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(107, Short.MAX_VALUE)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, -1, 50));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 790, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, -1, -1));

        comp_descr.setBackground(new java.awt.Color(153, 153, 153));
        comp_descr.setColumns(20);
        comp_descr.setLineWrap(true);
        comp_descr.setRows(5);
        comp_descr.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)), javax.swing.BorderFactory.createTitledBorder(null, "DESCRIPTION", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(102, 0, 102))), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED))); // NOI18N
        jScrollPane2.setViewportView(comp_descr);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 880, 140));

        jButton3.setText("<< BACK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 580, 100, -1));
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 630));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jList1.clearSelection();
        comp_ID.setText("");
        YEAR.setText("");
        sslcperc.setText("");
        pucperc.setText("");
        degagg.setText("");
        backlogs.setText("");
        degpass.setText("");
        comp_descr.setText("");
        jTextField1.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       
            
       if(jList1.isSelectionEmpty())
        {
                        JOptionPane.showMessageDialog(null,"Please select company name");
        }
        else if(YEAR.getText().equals(""))
        {
                        JOptionPane.showMessageDialog(null,"Please enter YEAR");
        }
        else if(sslcperc.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Please enter percentage of SSLC");
        }
      
        else if(pucperc.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Please enter percentage of PUC");
            
        }
        else if(degagg.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Please enter percentage of Degree");
            
        }
         else if(backlogs.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Please enter backlogs if any,otherwise enter 0");          
        }
         else if(degpass.getText().equals(""))
       {
            JOptionPane.showMessageDialog(null,"Please enter passing year of Degree");          
       }
         else if(jList1.isSelectedIndex(7)&&jTextField1.getText().equals(""))
        {
                                    JOptionPane.showMessageDialog(null,"Please Specify the company name");
        }
         else if(!(YEAR.getText().length() == 4))
        {
                     JOptionPane.showMessageDialog(null, "Enter the year in 'yyyy' Format");
                     YEAR.setText("");
         }
         else if(!(degpass.getText().length() == 4))
          {
                     JOptionPane.showMessageDialog(null, "Enter the year in 'yyyy' Format");
                     degpass.setText("");
                     
          }
          else if(backlogs.getText().length() > 2)
           {
                         JOptionPane.showMessageDialog(null, "The value is too long....");
                         backlogs.setText("");
          }
       else
         {
       int val1 =Integer.parseInt(YEAR.getText());
       int val2 = Integer.parseInt(degpass.getText());
       int val3 = val1+1;
             
        int val4=Integer.parseInt(sslcperc.getText());
        int val5 = 100;
        int val6=Integer.parseInt(pucperc.getText());
        int val7 = 100;
        int val8=Integer.parseInt(degagg.getText());
        int val9 = 100;
       
        if(!((val1==val2)||(val2==(val1+1))))
        {
                 JOptionPane.showMessageDialog(null,"Passing year of degree must be '"+val1+"' or '"+val3+"' Only");

            degpass.setText("");
        }
        else if(val4>val5)
        {
                        JOptionPane.showMessageDialog(null," '" +val4+ "' is not a valid percentage");   
                        sslcperc.setText("");
        }
        else if(val6>val7)
        {
                        JOptionPane.showMessageDialog(null," '" +val6+ "' is not a valid percentage");  
                        pucperc.setText("");
        }
        else if(val8>val9)
        {
                        JOptionPane.showMessageDialog(null," '" +val8+ "' is not a valid percentage"); 
                        degagg.setText("");
        }
        else
       {
          try
          {
              Class.forName("com.mysql.jdbc.Driver");
              Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/student","root","");
              PreparedStatement pst1;
              String query1;
                query1="SELECT * FROM `criteria` where comp_ID = ? LIMIT 0 , 30";
                pst1 = con.prepareStatement(query1);
                pst1.setString(1,comp_ID.getText());
                ResultSet rs1=pst1.executeQuery();
                if(rs1.next())
                {  

                            JOptionPane.showMessageDialog(null,"This ID is already used by the another company");
                            comp_ID.setText("");
                }
                else
                {                  
                        String sql;
                        PreparedStatement pst;
                        sql = "INSERT INTO `student`.`criteria` (`comp_ID`,`comp_name`,`YEAR`,`Crsslcperc`,`Crpucperc`,`Crdegagg`,`Crdegpass`,`Crbacklogs`,`comp_descr`)VALUES(?,?,?, ?, ?, ?, ?, ?,?)";
                        pst = con.prepareStatement(sql);
                        
                        pst.setString(1,comp_ID.getText());
                        switch (jList1.getSelectedIndex()) {
                               case 0:
                                   pst.setString(2,jList1.getSelectedValue());

                                   break;
                               case 1:
                                   pst.setString(2,jList1.getSelectedValue());

                                   break;
                               case 2:
                                  pst.setString(2,jList1.getSelectedValue());

                                   break;
                               case 3:
                                   pst.setString(2,jList1.getSelectedValue());

                                   break;
                               case 4:
                                   pst.setString(2,jList1.getSelectedValue());

                                   break;
                               case 5:
                                   pst.setString(2,jList1.getSelectedValue());

                                   break;
                               case 6:
                                   pst.setString(2,jList1.getSelectedValue());

                                   break;
                               default:
                                   pst.setString(2,jTextField1.getText());

                                   break;
                           }
                            pst.setString(3,YEAR.getText());
                            pst.setString(4,sslcperc.getText());
                            pst.setString(5,pucperc.getText());
                            pst.setString(6,degagg.getText());
                           
                            pst.setString(7,degpass.getText());
                            pst.setString(8,backlogs.getText());
                            pst.setString(9,comp_descr.getText());
                            pst.execute(); 
                            JOptionPane.showMessageDialog(null,"Success");
                            
            }
        }
        catch(HeadlessException | ClassNotFoundException | SQLException e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
       }             
         }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void sslcpercMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sslcpercMouseEntered
        // TODO add your handling code here:
        jLabel2.setForeground(Color.yellow);
    }//GEN-LAST:event_sslcpercMouseEntered

    private void sslcpercMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sslcpercMouseExited
        // TODO add your handling code here:
                jLabel2.setForeground(Color.black);
    }//GEN-LAST:event_sslcpercMouseExited

    private void pucpercMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pucpercMouseEntered
        // TODO add your handling code here:
                jLabel3.setForeground(Color.yellow);

    }//GEN-LAST:event_pucpercMouseEntered

    private void pucpercMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pucpercMouseExited
        // TODO add your handling code here:
                        jLabel3.setForeground(Color.black);

    }//GEN-LAST:event_pucpercMouseExited

    private void degaggMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_degaggMouseEntered
        // TODO add your handling code here:
                jLabel4.setForeground(Color.yellow);

    }//GEN-LAST:event_degaggMouseEntered

    private void degaggMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_degaggMouseExited
        // TODO add your handling code here:
                        jLabel4.setForeground(Color.black);

    }//GEN-LAST:event_degaggMouseExited

    private void degpassMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_degpassMouseEntered
        // TODO add your handling code here:
                        jLabel6.setForeground(Color.yellow);

    }//GEN-LAST:event_degpassMouseEntered

    private void degpassMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_degpassMouseExited
        // TODO add your handling code here:
                        jLabel6.setForeground(Color.black);

    }//GEN-LAST:event_degpassMouseExited

    private void backlogsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backlogsMouseEntered
        // TODO add your handling code here:
                jLabel5.setForeground(Color.yellow);

    }//GEN-LAST:event_backlogsMouseEntered

    private void backlogsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backlogsMouseExited
        // TODO add your handling code here:
                        jLabel5.setForeground(Color.black);

    }//GEN-LAST:event_backlogsMouseExited

    private void degpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_degpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_degpassActionPerformed

    private void sslcpercKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sslcpercKeyTyped
        // TODO add your handling code here:
       
         
       
    }//GEN-LAST:event_sslcpercKeyTyped

    private void pucpercKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pucpercKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_pucpercKeyTyped

    private void degaggKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_degaggKeyTyped
        // TODO add your handling code here:
          char c = evt.getKeyChar();
        if(Character.isDigit(c)||Character.isISOControl(c)||evt.isActionKey())
        {
            degagg.setEditable(true);
        }
        else
        {
            degagg.setEditable(false);
           
        }

    }//GEN-LAST:event_degaggKeyTyped

    private void degpassKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_degpassKeyTyped
        // TODO add your handling code here:
         char c = evt.getKeyChar();
        if(Character.isDigit(c)||Character.isISOControl(c)||evt.isActionKey())
        {
            degpass.setEditable(true);
        }
        else
        {
            degpass.setEditable(false);
           
        }

    }//GEN-LAST:event_degpassKeyTyped

    private void backlogsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_backlogsKeyTyped
        // TODO add your handling code here:
         char c = evt.getKeyChar();
        if(Character.isDigit(c)||Character.isISOControl(c)||evt.isActionKey())
        {
            backlogs.setEditable(true);
        }
        else
        {
            backlogs.setEditable(false);
           
        }
    }//GEN-LAST:event_backlogsKeyTyped

    private void sslcpercKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sslcpercKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(Character.isDigit(c)||Character.isISOControl(c)||evt.isActionKey())
        {
                            sslcperc.setEditable(true);
                        
        }
            
        
        else
        {
            sslcperc.setEditable(false);
           
        }
         
                
        
    }//GEN-LAST:event_sslcpercKeyPressed

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
        // TODO add your handling code here:
        if(!(jList1.isSelectedIndex(7)))
        {
                       jTextField1.setEditable(false);
        }
        else
        {
                      JOptionPane.showMessageDialog(null,"Specify it");
                      jTextField1.setEditable(true);

        }
    }//GEN-LAST:event_jList1ValueChanged

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        NewJFrame18 NN = new NewJFrame18();
        NN.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void YEARKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_YEARKeyPressed
        // TODO add your handling code here:
         char c = evt.getKeyChar();
        if(Character.isDigit(c)||Character.isISOControl(c)||evt.isActionKey())
        {
            YEAR.setEditable(true);
        }
        else
        {
            YEAR.setEditable(false);
           
        }
       
    }//GEN-LAST:event_YEARKeyPressed

    private void YEARKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_YEARKeyReleased
      
    }//GEN-LAST:event_YEARKeyReleased

    private void degpassKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_degpassKeyReleased
        // TODO add your handling code here:
     
    }//GEN-LAST:event_degpassKeyReleased

    private void pucpercKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pucpercKeyPressed
        // TODO add your handling code here:
         char a = evt.getKeyChar();
        if(Character.isDigit(a)||Character.isISOControl(a))
        {
            pucperc.setEditable(true);
        }
        else
        {
            pucperc.setEditable(false);
            JOptionPane.showMessageDialog(null,"Accepts Numbers Only");
                        pucperc.setEditable(true);

        }

    }//GEN-LAST:event_pucpercKeyPressed

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        // TODO add your handling code here:
        if(!(jList1.isSelectedIndex(7)))
      {
          jTextField1.setText("");
      }
        
    }//GEN-LAST:event_jList1MouseClicked

    private void comp_IDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_comp_IDKeyPressed
        // TODO add your handling code here:
         char c = evt.getKeyChar();
        if(Character.isDigit(c)||Character.isISOControl(c)||evt.isActionKey())
        {
            comp_ID.setEditable(true);
        }
        else
        {
            comp_ID.setEditable(false);
           
        }
    }//GEN-LAST:event_comp_IDKeyPressed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        // TODO add your handling code here:
         char c = evt.getKeyChar();
        if(Character.isLetter(c)||Character.isWhitespace(c)||Character.isISOControl(c)||evt.isActionKey())
        {
            jTextField1.setEditable(true);
        }
        else
        {
            jTextField1.setEditable(false);

        }
    }//GEN-LAST:event_jTextField1KeyPressed

    private void sslcpercMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sslcpercMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_sslcpercMouseMoved

    private void sslcpercMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sslcpercMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_sslcpercMousePressed

    private void sslcpercMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sslcpercMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_sslcpercMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CRITERIA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CRITERIA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CRITERIA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CRITERIA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CRITERIA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField YEAR;
    private javax.swing.JTextField backlogs;
    private javax.swing.JTextField comp_ID;
    private javax.swing.JTextArea comp_descr;
    private javax.swing.JTextField degagg;
    private javax.swing.JTextField degpass;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField pucperc;
    private javax.swing.JTextField sslcperc;
    // End of variables declaration//GEN-END:variables
}
