/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication3;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class GENTEST extends javax.swing.JFrame {

    /**
     * Creates new form GENTEST
     */
    public GENTEST() {
        initComponents();
        tableupdate();
        jButton2.setVisible(false);
        jLabel3.setVisible(false);
    }
    public GENTEST(String aa) {
         

        initComponents();
        
        tableupdate();

        jLabel3.setText(aa);
        jLabel3.setVisible(false);
        jButton1.setVisible(false);
        jButton2.setVisible(true);
    }
     private void tableupdate()
    {
        try
        {       
                Class.forName("com.mysql.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/student","root","");
                  String query1="SELECT DISTINCT `comp_ID`,`Test_ID`,`Test_Name`,`HR`,`MN` FROM `APTTEST` ";
                    PreparedStatement pst;
                    pst = con.prepareStatement(query1);
                    ResultSet rs1=pst.executeQuery();
                   ResultSetMetaData Rss = rs1.getMetaData();
                   int p = Rss.getColumnCount();
                           DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                     model.setRowCount(0);
                     while(rs1.next())
                     {
                          Vector v2 = new Vector();
                          
                          for(int a=1;a<=p;a++)
                          {
                            v2.add(rs1.getString(1));
                            v2.add(rs1.getString(2));
                            v2.add(rs1.getString(3));
                            v2.add(rs1.getString(4));
                            v2.add(rs1.getString(5));
                            
                            
                          }
                        model.addRow(v2);
                         
                     }     
                     
            }
         catch(HeadlessException | ClassNotFoundException | SQLException e)
        {
                JOptionPane.showMessageDialog(null,e);
        }
    
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        Test_ID = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        TQ = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        COMP = new javax.swing.JLabel();
        YEAR = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ALL GENERATED TESTS");

        jLabel3.setText("jLabel3");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(406, 406, 406)
                .addComponent(jLabel1)
                .addGap(244, 244, 244)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addGap(47, 47, 47))
        );

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setBackground(new java.awt.Color(204, 204, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Company ID", "Test ID", "Test Name", "HOUR", "MINUTES"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 650, 450));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton1.setText("VIEW TEST");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Enter Test ID:");

        jButton2.setText("ATTEND TEST");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Test_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Test_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 460, 530, 130));

        jLabel4.setBackground(new java.awt.Color(204, 255, 204));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 255, 204));
        jLabel4.setText("Total Questions :");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        TQ.setEditable(false);
        TQ.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        TQ.setForeground(new java.awt.Color(255, 0, 0));
        TQ.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TQ.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.add(TQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 60, 41));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 255, 204));
        jLabel7.setText("Company :");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        COMP.setBackground(new java.awt.Color(204, 204, 204));
        COMP.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        COMP.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        COMP.setOpaque(true);
        jPanel3.add(COMP, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 140, 40));

        YEAR.setBackground(new java.awt.Color(204, 204, 204));
        YEAR.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        YEAR.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        YEAR.setOpaque(true);
        jPanel3.add(YEAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 140, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication3/CMafWZX-professional-desktop-wallpaper.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -6, 1150, 650));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
      if(Test_ID.getText().equals(""))
          {
              JOptionPane.showMessageDialog(null,"Please  enter valid Test ID");
        }
      else
          
         {
            try
                {

                    Class.forName("com.mysql.jdbc.Driver");
                    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/student","root","");
                    String sql,sql1,sql2,sql3,sql4;
                    PreparedStatement pst,pst1,pst2,pst3,pst4;
                    sql2="SELECT * FROM `APTTEST` where Test_ID = ? LIMIT 0 , 30";
                        pst2 = con.prepareStatement(sql2);
                        pst2.setString(1,Test_ID.getText());
                        ResultSet rs2=pst2.executeQuery();
                        if(rs2.next())
                        {
                                  String comp = rs2.getString(1);
                                  String TestName = rs2.getString(3);

                                  String usern = Test_ID.getText();
                                  int PG = 1;
                                  int TPG = 0;
                                  int m =1;
                                  int n=0;
                                  new APTTEST(usern,comp,TestName,PG,TPG,m,n).setVisible(true);

                            
                        }
                        else
                        {
                                        JOptionPane.showMessageDialog(null,"Test ID Not found");
                                            Test_ID.setText("");
                        }
                    }      
          catch(HeadlessException | ClassNotFoundException | SQLException e)
          {
            JOptionPane.showMessageDialog(null,e);
          }
            }
            
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int TOTPG = 0,HR = 0,MN=0;
        String comp = null,TestName = null;
    if(Test_ID.getText().equals(""))
          {
              JOptionPane.showMessageDialog(null,"Please  enter valid Test ID");
        }
      else
          
         {
        try
                {

                    Class.forName("com.mysql.jdbc.Driver");
                    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/student","root","");
                    String sql,sql1,sql2,sql3,sql4;
                    PreparedStatement pst,pst1,pst2,pst3,pst4;
                    
                    
                        sql2="SELECT * FROM `APTTEST` where Test_ID = ?  LIMIT 0 , 30";
                        pst2 = con.prepareStatement(sql2);
                        pst2.setString(1,Test_ID.getText());
                        ResultSet rs2=pst2.executeQuery();
                        if(rs2.next())
                        {
                           
                                   comp = rs2.getString(1);
                                   TestName = rs2.getString(3);
                                    HR = rs2.getInt(13);
                                    MN = rs2.getInt(14);
                            
                        }  
                                sql3="SELECT * FROM `ANSTEST` where Test_ID = ? AND stdid = ? LIMIT 0 , 30";
                                pst3 = con.prepareStatement(sql3);
                                pst3.setString(1,Test_ID.getText());
                                pst3.setString(2,jLabel3.getText());
                                
                                ResultSet rs3=pst3.executeQuery();
                                if(rs3.next())
                                {
                                    JOptionPane.showMessageDialog(null,"You have already attended the test");
 
                                }
                                else
                                {
                                
                                  String stdid = jLabel3.getText();
                                  String usern = Test_ID.getText();
                                  int PGNO =1;
                                  int m =1;
                                  int n=0;
                                  int s=0;
                                  new ANSAPT(usern,comp,TestName,stdid,PGNO,TOTPG,m,n,HR,MN,s).setVisible(true); 
                                  dispose();
                                }
                            
                        
                        
                    }      
          catch(HeadlessException | ClassNotFoundException | SQLException e)
          {
            JOptionPane.showMessageDialog(null,e);
          }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int selectedIndex = jTable1.getSelectedRow();
        String TESTID = model.getValueAt(selectedIndex,1).toString();
        Test_ID.setText(TESTID);
        String COM = model.getValueAt(selectedIndex,0).toString();
        try
        {
             int a=0;
                    Class.forName("com.mysql.jdbc.Driver");
                    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/student","root","");

                   String sql3 = "SELECT  * from `student`.`APTTEST` WHERE `Test_ID` = ?";
                    PreparedStatement pst3 = con.prepareStatement(sql3);
                     int selectedIndex1 = jTable1.getSelectedRow();
                    String TESTID1 = model.getValueAt(selectedIndex,1).toString();
                    pst3.setString(1,TESTID1);
                    ResultSet rs3  = pst3.executeQuery();
                    while(rs3.next())
                    {  
                        a++;
                    }
                    TQ.setText(""+a);
                    String sql4 = "SELECT * from `student`.`CRITERIA` WHERE `comp_ID` = ?";
                    PreparedStatement pst4 = null;
                    pst4 = con.prepareStatement(sql4);
                    pst4.setString(1,COM);
                    ResultSet rs4  = pst4.executeQuery();
                    if(rs4.next())
                    {
                        COMP.setText(rs4.getString(2));
                        YEAR.setText(rs4.getString(3));
                    }
 
            
        }
         catch(HeadlessException | ClassNotFoundException | SQLException e)
          {
            JOptionPane.showMessageDialog(null,e);
          }
        
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GENTEST.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GENTEST.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GENTEST.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GENTEST.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GENTEST().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel COMP;
    private javax.swing.JTextField TQ;
    private javax.swing.JTextField Test_ID;
    private javax.swing.JLabel YEAR;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
