/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication3;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author User
 */
public class NewJFrame6 extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame6
     */
    public NewJFrame6() {
       
        setUndecorated(true);
        initComponents();
        ((JTextField)dob.getDateEditor().getUiComponent()).setEditable(false);
         setBackground(new Color(0.0f,0.0f,0.0f,0.0f));

      }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollbar1 = new java.awt.Scrollbar();
        jMenuItem1 = new javax.swing.JMenuItem();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        sname = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        stdid = new javax.swing.JTextField();
        mname = new javax.swing.JTextField();
        fname = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        clname = new javax.swing.JTextField();
        degagg = new javax.swing.JTextField();
        degpass = new javax.swing.JTextField();
        sslcperc = new javax.swing.JTextField();
        sslcpass = new javax.swing.JTextField();
        pucperc = new javax.swing.JTextField();
        pucpass = new javax.swing.JTextField();
        backlogs = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        STDVAL = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        SECURQS = new javax.swing.JTextField();
        jFileChooser1 = new javax.swing.JFileChooser();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        dob = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        jMenuItem1.setText("jMenuItem1");

        setBackground(new java.awt.Color(255, 102, 102));
        setLocation(new java.awt.Point(190, 50));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setPreferredSize(new java.awt.Dimension(13840, 8390));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("STUDENT NAME");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 53, 203, 25));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("PASSWORD");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 93, 203, 28));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("STUDENT ID");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 132, 124, 27));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("MOTHER NAME");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
        });
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 171, 203, 28));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("FATHER NAME");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
        });
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 212, 113, 35));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("GENDER");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel6MouseEntered(evt);
            }
        });
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 257, 113, 33));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("DOB");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel7MouseEntered(evt);
            }
        });
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 113, 27));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("EMAIL ID");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel8MouseEntered(evt);
            }
        });
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, 113, 32));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("COLLEGE NAME");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel9MouseEntered(evt);
            }
        });
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 413, 113, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("DEGREE MARKS");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel10MouseEntered(evt);
            }
        });
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 460, 150, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("PASS YEAR GRADUATION");
        jLabel11.setToolTipText("PASS");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel11MouseEntered(evt);
            }
        });
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 503, 203, 27));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("10TH PERCENTAGE");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel12MouseEntered(evt);
            }
        });
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 540, 185, 33));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("PASS YEAR SSLC");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel13MouseEntered(evt);
            }
        });
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 580, 185, 32));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("12TH PERCENTAGE");
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel15MouseEntered(evt);
            }
        });
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 629, 185, 27));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("PASS YEAR PUC");
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel16MouseEntered(evt);
            }
        });
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 670, 146, 30));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("BACKLOGS");
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel17MouseEntered(evt);
            }
        });
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 721, 94, 22));

        sname.setBackground(new java.awt.Color(153, 153, 153));
        sname.setToolTipText("ENTER STUDENT NAME");
        sname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        sname.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                snameCaretUpdate(evt);
            }
        });
        sname.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                snameMouseMoved(evt);
            }
        });
        sname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                snameFocusLost(evt);
            }
        });
        sname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                snameMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                snameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                snameMouseExited(evt);
            }
        });
        sname.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                snameInputMethodTextChanged(evt);
            }
        });
        sname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                snameActionPerformed(evt);
            }
        });
        sname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                snameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                snameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                snameKeyTyped(evt);
            }
        });
        jPanel1.add(sname, new org.netbeans.lib.awtextra.AbsoluteConstraints(431, 45, 290, 29));

        password.setBackground(new java.awt.Color(153, 153, 153));
        password.setToolTipText("ENTER THE PASSWORD");
        password.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        password.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                passwordCaretUpdate(evt);
            }
        });
        password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passwordMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                passwordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                passwordMouseExited(evt);
            }
        });
        password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordKeyPressed(evt);
            }
        });
        jPanel1.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(431, 93, 290, 28));

        stdid.setBackground(new java.awt.Color(153, 153, 153));
        stdid.setToolTipText("ENTER THE STUDENT ID");
        stdid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        stdid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                stdidFocusGained(evt);
            }
        });
        stdid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                stdidMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                stdidMouseExited(evt);
            }
        });
        stdid.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                stdidInputMethodTextChanged(evt);
            }
        });
        stdid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stdidActionPerformed(evt);
            }
        });
        stdid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                stdidKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                stdidKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                stdidKeyTyped(evt);
            }
        });
        jPanel1.add(stdid, new org.netbeans.lib.awtextra.AbsoluteConstraints(431, 132, 290, 28));

        mname.setBackground(new java.awt.Color(153, 153, 153));
        mname.setToolTipText("ENTER THE MOTHER NAME");
        mname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        mname.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        mname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                mnameFocusGained(evt);
            }
        });
        mname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mnameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mnameMouseExited(evt);
            }
        });
        mname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnameActionPerformed(evt);
            }
        });
        mname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                mnameKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mnameKeyTyped(evt);
            }
        });
        jPanel1.add(mname, new org.netbeans.lib.awtextra.AbsoluteConstraints(431, 171, 290, 28));

        fname.setBackground(new java.awt.Color(153, 153, 153));
        fname.setToolTipText("ENTER THE FATHER NAME");
        fname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                fnameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                fnameMouseExited(evt);
            }
        });
        fname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fnameKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fnameKeyTyped(evt);
            }
        });
        jPanel1.add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(431, 210, 290, 29));

        email.setBackground(new java.awt.Color(153, 153, 153));
        email.setToolTipText("ENTER THE EMAIL ID");
        email.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        email.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emailMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                emailMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                emailMouseExited(evt);
            }
        });
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                emailKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                emailKeyReleased(evt);
            }
        });
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(431, 365, 290, 30));

        clname.setBackground(new java.awt.Color(153, 153, 153));
        clname.setToolTipText("ENTER THE COLLAGE NAME");
        clname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        clname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clnameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                clnameMouseExited(evt);
            }
        });
        clname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                clnameKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                clnameKeyTyped(evt);
            }
        });
        jPanel1.add(clname, new org.netbeans.lib.awtextra.AbsoluteConstraints(431, 410, 290, 30));

        degagg.setBackground(new java.awt.Color(153, 153, 153));
        degagg.setToolTipText("ENTER THE DEGREE AGGRIGATE");
        degagg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        degagg.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                degaggFocusLost(evt);
            }
        });
        degagg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                degaggMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                degaggMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                degaggMouseExited(evt);
            }
        });
        degagg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                degaggKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                degaggKeyTyped(evt);
            }
        });
        jPanel1.add(degagg, new org.netbeans.lib.awtextra.AbsoluteConstraints(431, 458, 290, 33));

        degpass.setBackground(new java.awt.Color(153, 153, 153));
        degpass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        degpass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                degpassFocusLost(evt);
            }
        });
        degpass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                degpassMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                degpassMouseExited(evt);
            }
        });
        degpass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                degpassKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                degpassKeyTyped(evt);
            }
        });
        jPanel1.add(degpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(431, 505, 290, 30));

        sslcperc.setBackground(new java.awt.Color(153, 153, 153));
        sslcperc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        sslcperc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sslcpercMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sslcpercMouseExited(evt);
            }
        });
        sslcperc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sslcpercActionPerformed(evt);
            }
        });
        sslcperc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                sslcpercKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                sslcpercKeyTyped(evt);
            }
        });
        jPanel1.add(sslcperc, new org.netbeans.lib.awtextra.AbsoluteConstraints(431, 546, 290, 32));

        sslcpass.setBackground(new java.awt.Color(153, 153, 153));
        sslcpass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        sslcpass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sslcpassMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sslcpassMouseExited(evt);
            }
        });
        sslcpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sslcpassActionPerformed(evt);
            }
        });
        sslcpass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                sslcpassKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                sslcpassKeyTyped(evt);
            }
        });
        jPanel1.add(sslcpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(431, 589, 290, 29));

        pucperc.setBackground(new java.awt.Color(153, 153, 153));
        pucperc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pucperc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pucpercMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pucpercMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pucpercMouseExited(evt);
            }
        });
        pucperc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pucpercKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pucpercKeyTyped(evt);
            }
        });
        jPanel1.add(pucperc, new org.netbeans.lib.awtextra.AbsoluteConstraints(431, 630, 290, 29));

        pucpass.setBackground(new java.awt.Color(153, 153, 153));
        pucpass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pucpass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pucpassMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pucpassMouseExited(evt);
            }
        });
        pucpass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pucpassKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pucpassKeyTyped(evt);
            }
        });
        jPanel1.add(pucpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(431, 673, 290, 29));

        backlogs.setBackground(new java.awt.Color(153, 153, 153));
        backlogs.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        backlogs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backlogsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backlogsMouseExited(evt);
            }
        });
        backlogs.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                backlogsKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                backlogsKeyTyped(evt);
            }
        });
        jPanel1.add(backlogs, new org.netbeans.lib.awtextra.AbsoluteConstraints(431, 713, 290, 30));

        jButton1.setBackground(new java.awt.Color(204, 255, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("SUBMIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 810, 108, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("CLEAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 810, 108, -1));

        jButton3.setBackground(new java.awt.Color(204, 204, 204));
        jButton3.setText("<< BACK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 810, 108, -1));

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadioButton3.setForeground(new java.awt.Color(51, 51, 255));
        jRadioButton3.setText("MALE");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 270, 95, -1));

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadioButton4.setForeground(new java.awt.Color(0, 0, 204));
        jRadioButton4.setText("FEMALE");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 270, 94, -1));

        STDVAL.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        STDVAL.setForeground(new java.awt.Color(204, 0, 204));
        STDVAL.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.add(STDVAL, new org.netbeans.lib.awtextra.AbsoluteConstraints(828, 165, 115, 20));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 0, 0));
        jLabel18.setText("Enter Your Favourate Fruit");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 754, 203, 34));

        SECURQS.setBackground(new java.awt.Color(153, 153, 153));
        SECURQS.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(102, 102, 102), null, null));
        SECURQS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SECURQSMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SECURQSMouseExited(evt);
            }
        });
        SECURQS.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                SECURQSKeyPressed(evt);
            }
        });
        jPanel1.add(SECURQS, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 760, 290, 35));

        jFileChooser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFileChooser1ActionPerformed(evt);
            }
        });
        jPanel1.add(jFileChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, -90, -1, 70));

        jCheckBox1.setText("Show Password");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 100, -1, 20));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("yyyy Format");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 510, 80, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("yyyy Format");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 594, 80, 20));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("yyyy Format");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 680, 80, -1));

        dob.setDateFormatString("yyyy-MM-dd");
        jPanel1.add(dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 320, 290, 30));

        jScrollPane2.setViewportView(jPanel1);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 0));
        jLabel14.setText("REGISTRATION FORM");

        jButton4.setText("X");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(302, 302, 302)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 977, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jFileChooser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileChooser1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFileChooser1ActionPerformed

    private void dobKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dobKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_dobKeyPressed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        NewJFrame4 tt=new NewJFrame4();
        tt.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        sname.setText("");
        password.setText("");
        stdid.setText("");
        mname.setText("");
        fname.setText("");
        ((JTextField)dob.getDateEditor().getUiComponent()).setText("");
        email.setText("");
        clname.setText("");
        degagg.setText("");
        degpass.setText("");
        sslcperc.setText("");
        sslcpass.setText("");
        pucperc.setText("");
        pucpass.setText("");
        backlogs.setText("");
        SECURQS.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

   
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
         SimpleDateFormat txtDate = new SimpleDateFormat("yyyy");
         Date date = new Date();
         int dt = Integer.parseInt(txtDate.format(date));
        
        String s="@gmail.com";
        
        if(sname.getText().equals(""))
         {
            JOptionPane.showMessageDialog(null,"Student name can't be empty");
         }
        else if(password.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Please enter password");
        }
        else if(stdid.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Student ID can't be empty");
        }
        else if(mname.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Mother name can't be empty");
        }
        else if(fname.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"father name can't be empty");
        }
        else if(!(jRadioButton3.isSelected()||jRadioButton4.isSelected()))
        {
            JOptionPane.showMessageDialog(null,"Please select Gender");
        }
        else if(((JTextField)dob.getDateEditor().getUiComponent()).getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Please select Date of Birth");
        }

        else if(email.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Email can't be empty");
         }
        else if(!(email.getText().contains(s)))
        {
            JOptionPane.showMessageDialog(null,"'@gmail.com' to be include in Email");
            email.setText("");
        }
        else if(clname.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"College name can't be empty");
        }
        else if(degagg.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Please enter Degree aggregate");
        }

        else if(degpass.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Please enter passing year of degree");
        }
        else if(sslcperc.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Please enter SSLC percentage");
        }
        else if(sslcpass.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Please enter SSLC passing year");
        }
        else if(pucperc.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Please enter PUC percentage");
        }
        else if(pucpass.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Please enter PUC passing year");
        }
        else if(backlogs.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Please enter backlogs,if not enter 0");
        }
        else if(SECURQS.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Please enter your favourate fruit");
        }
    else

             {
            
            int val4=Integer.parseInt(sslcperc.getText());
            int val5 = 100;
            int val6=Integer.parseInt(pucperc.getText());
            int val7 = 100;
            int val8=Integer.parseInt(degagg.getText());
            int val9 = 100;

             int dt2=Integer.parseInt(pucpass.getText()); 
             int dt3=Integer.parseInt(sslcpass.getText());           

            if(val4>val5)
            {
                            JOptionPane.showMessageDialog(null," '" +val4+ "' is not a valid percentage");   
                            sslcperc.setText("");

            }
            else if(val6>val7)
            {
                            JOptionPane.showMessageDialog(null," '" +val6+ "' is not a valid percentage");  
                            pucperc.setText("");
            }
            else if(val8>val9)
            {
                            JOptionPane.showMessageDialog(null," '" +val8+ "' is not a valid percentage"); 
                            degagg.setText("");
            }
             
            else if(!(degpass.getText().length() == 4))
                 {
                     JOptionPane.showMessageDialog(null, "Enter the year in 'yyyy' Format");
                     degpass.setText("");
                 }
            else if(!(sslcpass.getText().length() == 4))
                     {
                         JOptionPane.showMessageDialog(null, "Enter the year in 'yyyy' Format");
                         sslcpass.setText("");
                     }
             else if(!(pucpass.getText().length() == 4))
                     {
                         JOptionPane.showMessageDialog(null, "Enter the year in 'yyyy' Format");
                         pucpass.setText("");
                     }
             else if(backlogs.getText().length() > 2)
                     {
                         JOptionPane.showMessageDialog(null, "The value is too long....");
                         backlogs.setText("");
                     }
             
             else if( dt2>dt||dt3>dt)
             {
                   JOptionPane.showMessageDialog(null, "Entered year is greater then the current year ");
              }
            else
             {
          
                try
                {

                    Class.forName("com.mysql.jdbc.Driver");
                    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/student","root","");
                    String sql,sql1;
                    PreparedStatement pst,pst1;

                    sql1 = "SELECT *FROM `stdreg` WHERE stdid = ? LIMIT 0 , 30";
                    pst1 = con.prepareStatement(sql1);
                    pst1.setString(1,stdid.getText());
                    
                    ResultSet rs=pst1.executeQuery();
                    if(rs.next())
                    {
                        JOptionPane.showMessageDialog(null,"This ID is already hold by another student");
                        JOptionPane.showMessageDialog(null,"Please enter valid ID");
                        stdid.setText("");
                    }
                    else
                    {

                        sql = "INSERT INTO `student`.`stdreg` (`sname`,`password`,`stdid`,`mname`,`fname`,`gender`,`dob`,`email`,`clname`,`degagg`,`degpass`,`sslcperc`,`sslcpass`,`pucperc`,`pucpass`,`backlogs`,`securityqs`,`feedback`)VALUES(?,?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,'')";
                        pst = con.prepareStatement(sql);
                        pst.setString(1,sname.getText());
                        pst.setString(2,password.getText());
                        pst.setString(3,stdid.getText());
                        pst.setString(4,mname.getText());
                        pst.setString(5,fname.getText());

                        if(jRadioButton3.isSelected())
                        {
                            pst.setString(6,jRadioButton3.getText());
                        }
                        if(jRadioButton4.isSelected())
                        {
                            pst.setString(6,jRadioButton4.getText());
                        }
                        pst.setString(7,((JTextField)dob.getDateEditor().getUiComponent()).getText());
                        pst.setString(8,email.getText());
                        pst.setString(9,clname.getText());
                        pst.setString(10,degagg.getText());
                        pst.setString(11,degpass.getText());
                        pst.setString(12,sslcperc.getText());
                        pst.setString(13,sslcpass.getText());
                        pst.setString(14,pucperc.getText());
                        pst.setString(15,pucpass.getText());
                        pst.setString(16,backlogs.getText());
                        pst.setString(17,SECURQS.getText());

                        pst.execute();

                        JOptionPane.showMessageDialog(null,"Registeration Successful");
                        sname.setText("");
                        password.setText("");
                        stdid.setText("");
                        mname.setText("");
                        fname.setText("");
                        ((JTextField)dob.getDateEditor().getUiComponent()).setText("");
                        email.setText("");
                        clname.setText("");
                        degagg.setText("");
                        degpass.setText("");
                        sslcperc.setText("");
                        sslcpass.setText("");
                        pucperc.setText("");
                        pucpass.setText("");
                        backlogs.setText("");
                        SECURQS.setText("");
                    }

                }
                catch(HeadlessException | ClassNotFoundException | SQLException e )
                {
                    JOptionPane.showMessageDialog(null,e);
                }
            }
             
    
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void backlogsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_backlogsKeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_backlogsKeyTyped

    private void backlogsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_backlogsKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(Character.isDigit(c)||Character.isISOControl(c)||evt.isActionKey())
        {
            backlogs.setEditable(true);
        }
        else
        {
            backlogs.setEditable(false);

        }
    }//GEN-LAST:event_backlogsKeyPressed

    private void backlogsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backlogsMouseExited
        // TODO add your handling code here:
        jLabel17.setForeground(Color.black );
         backlogs.setLocation(431, 713);
    }//GEN-LAST:event_backlogsMouseExited

    private void backlogsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backlogsMouseEntered
        // TODO add your handling code here:
        jLabel17.setForeground(Color.red);
         backlogs.setLocation(331, 713);
    }//GEN-LAST:event_backlogsMouseEntered

    private void pucpassKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pucpassKeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_pucpassKeyTyped

    private void pucpassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pucpassKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(Character.isDigit(c)||Character.isISOControl(c)||evt.isActionKey())
        {
            pucpass.setEditable(true);
        }
        else
        {
            pucpass.setEditable(false);

        }
    }//GEN-LAST:event_pucpassKeyPressed

    private void pucpassMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pucpassMouseExited
        // TODO add your handling code here:
        jLabel16.setForeground(Color.black );
         pucpass.setLocation(431, 673);
    }//GEN-LAST:event_pucpassMouseExited

    private void pucpassMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pucpassMouseEntered
        // TODO add your handling code here:
        jLabel16.setForeground(Color.red);
         pucpass.setLocation(331, 673);
    }//GEN-LAST:event_pucpassMouseEntered

    private void pucpercKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pucpercKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_pucpercKeyTyped

    private void pucpercKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pucpercKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(Character.isDigit(c)||Character.isISOControl(c)||evt.isActionKey())
        {
            pucperc.setEditable(true);
            
        }
        else
        {
            pucperc.setEditable(false);

        }
    }//GEN-LAST:event_pucpercKeyPressed

    private void pucpercMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pucpercMouseExited
        // TODO add your handling code here:
        jLabel15.setForeground(Color.black );
         pucperc.setLocation(431, 630);
    }//GEN-LAST:event_pucpercMouseExited

    private void pucpercMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pucpercMouseEntered
        // TODO add your handling code here:
        jLabel15.setForeground(Color.red);
         pucperc.setLocation(331, 630);
    }//GEN-LAST:event_pucpercMouseEntered

    private void sslcpassKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sslcpassKeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_sslcpassKeyTyped

    private void sslcpassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sslcpassKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(Character.isDigit(c)||Character.isISOControl(c)||evt.isActionKey())
        {
            sslcpass.setEditable(true);
            
        }
        else
        {
            sslcpass.setEditable(false);

        }
    }//GEN-LAST:event_sslcpassKeyPressed

    private void sslcpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sslcpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sslcpassActionPerformed

    private void sslcpassMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sslcpassMouseExited
        // TODO add your handling code here:
        jLabel13.setForeground(Color.black );
         sslcpass.setLocation(431, 589);
    }//GEN-LAST:event_sslcpassMouseExited

    private void sslcpassMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sslcpassMouseEntered
        // TODO add your handling code here:
        jLabel13.setForeground(Color.red);
         sslcpass.setLocation(331, 589);
    }//GEN-LAST:event_sslcpassMouseEntered

    private void sslcpercKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sslcpercKeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_sslcpercKeyTyped

    private void sslcpercKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sslcpercKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(Character.isDigit(c)||Character.isISOControl(c)||evt.isActionKey())
        {
            sslcperc.setEditable(true);
             
        }
        else
        {
            sslcperc.setEditable(false);

        }
    }//GEN-LAST:event_sslcpercKeyPressed

    private void sslcpercActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sslcpercActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sslcpercActionPerformed

    private void sslcpercMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sslcpercMouseExited
        // TODO add your handling code here:
        jLabel12.setForeground(Color.black );
         sslcperc.setLocation(431, 546);
    }//GEN-LAST:event_sslcpercMouseExited

    private void sslcpercMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sslcpercMouseEntered
        // TODO add your handling code here:
        jLabel12.setForeground(Color.red);
         sslcperc.setLocation(331, 546);
    }//GEN-LAST:event_sslcpercMouseEntered

    private void degpassKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_degpassKeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_degpassKeyTyped

    private void degpassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_degpassKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(Character.isDigit(c)||Character.isISOControl(c)||evt.isActionKey())
        {
            degpass.setEditable(true);
             
        }
        else
        {
            degpass.setEditable(false);

        }
    }//GEN-LAST:event_degpassKeyPressed

    private void degpassMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_degpassMouseExited
        // TODO add your handling code here:
        jLabel11.setForeground(Color.black );
         degpass.setLocation(431, 505);
    }//GEN-LAST:event_degpassMouseExited

    private void degpassMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_degpassMouseEntered
        // TODO add your handling code here:
        jLabel11.setForeground(Color.red);
         degpass.setLocation(331, 505);
    }//GEN-LAST:event_degpassMouseEntered

    private void degaggKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_degaggKeyTyped

        // TODO add your handling code here:

         
    }//GEN-LAST:event_degaggKeyTyped

    private void degaggKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_degaggKeyPressed
        // TODO add your handling code here:
       
        char c = evt.getKeyChar();
        if(Character.isDigit(c)||Character.isISOControl(c)||evt.isActionKey())
        {
            degagg.setEditable(true);
            
        }
        else
        {
            degagg.setEditable(false);

        }

    }//GEN-LAST:event_degaggKeyPressed

    private void degaggMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_degaggMouseExited
        // TODO add your handling code here:
        jLabel10.setForeground(Color.black );
         degagg.setLocation(431, 458);
    }//GEN-LAST:event_degaggMouseExited

    private void degaggMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_degaggMouseEntered
        // TODO add your handling code here:
        jLabel10.setForeground(Color.red);
         degagg.setLocation(331, 458);
    }//GEN-LAST:event_degaggMouseEntered

    private void clnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_clnameKeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_clnameKeyTyped

    private void clnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_clnameKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(Character.isLetter(c)||Character.isWhitespace(c)||Character.isISOControl(c)||evt.isActionKey())
        {
            clname.setEditable(true);
            
        }
        else
        {
            clname.setEditable(false);

        }
    }//GEN-LAST:event_clnameKeyPressed

    private void clnameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clnameMouseExited
        // TODO add your handling code here:
        jLabel9.setForeground(Color.black );
         clname.setLocation(431, 410);
    }//GEN-LAST:event_clnameMouseExited

    private void clnameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clnameMouseEntered
        // TODO add your handling code here:
        jLabel9.setForeground(Color.red);
         clname.setLocation(331, 410);
    }//GEN-LAST:event_clnameMouseEntered

    private void emailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_emailKeyReleased

    private void emailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailKeyPressed
        // TODO add your handling code here:
         

    }//GEN-LAST:event_emailKeyPressed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void emailMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailMouseExited
        // TODO add your handling code here:
        jLabel8.setForeground(Color.black );
         email.setLocation(431, 365);
    }//GEN-LAST:event_emailMouseExited

    private void emailMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailMouseEntered
        // TODO add your handling code here:
        jLabel8.setForeground(Color.red);
         email.setLocation(331, 365);
    }//GEN-LAST:event_emailMouseEntered

    private void emailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailMouseClicked
        // TODO add your handling code here:
        String mail = "@gmail.com";
        email.setText(mail);
        email.setCaretPosition(0);

    }//GEN-LAST:event_emailMouseClicked

    private void fnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fnameKeyTyped

        // TODO add your handling code here:
    }//GEN-LAST:event_fnameKeyTyped

    private void fnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fnameKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(Character.isLetter(c)||Character.isWhitespace(c)||Character.isISOControl(c)||evt.isActionKey())
        {
            fname.setEditable(true);
             
        }
        else
        {
            fname.setEditable(false);

        }
    }//GEN-LAST:event_fnameKeyPressed

    private void fnameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fnameMouseExited
        // TODO add your handling code here:
        jLabel5.setForeground(Color.black );
         fname.setLocation(431, 210);
    }//GEN-LAST:event_fnameMouseExited

    private void fnameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fnameMouseEntered
        // TODO add your handling code here:
        jLabel5.setForeground(Color.red);
         fname.setLocation(331, 210);
    }//GEN-LAST:event_fnameMouseEntered

    private void mnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mnameKeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_mnameKeyTyped

    private void mnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mnameKeyPressed
        // TODO add your handling code here:

        char c = evt.getKeyChar();
        if(Character.isLetter(c)||Character.isWhitespace(c)||Character.isISOControl(c)||evt.isActionKey())
        {
            mname.setEditable(true);
                }
        else
        {
            mname.setEditable(false);

        }
    }//GEN-LAST:event_mnameKeyPressed

    private void mnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnameActionPerformed

    private void mnameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnameMouseExited
        // TODO add your handling code here:
        jLabel4.setForeground(Color.black );
         mname.setLocation(431,171);
    }//GEN-LAST:event_mnameMouseExited

    private void mnameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnameMouseEntered
        // TODO add your handling code here:
        jLabel4.setForeground(Color.red);
         mname.setLocation(331, 171);
    }//GEN-LAST:event_mnameMouseEntered

    private void stdidKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_stdidKeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_stdidKeyTyped

    private void stdidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_stdidKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_stdidKeyReleased

    private void stdidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_stdidKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(Character.isDigit(c)||Character.isISOControl(c)||evt.isActionKey())
        {
            stdid.setEditable(true);
             
        }
        else
        {
            stdid.setEditable(false);

        }
    }//GEN-LAST:event_stdidKeyPressed

    private void stdidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stdidActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_stdidActionPerformed

    private void stdidInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_stdidInputMethodTextChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_stdidInputMethodTextChanged

    private void stdidMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stdidMouseExited
        // TODO add your handling code here:
        jLabel3.setForeground(Color.black);
         stdid.setLocation(431, 132);
        
    }//GEN-LAST:event_stdidMouseExited

    private void stdidMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stdidMouseEntered
        // TODO add your handling code here:
        jLabel3.setForeground(Color.red);
        stdid.setLocation(331, 132);
    }//GEN-LAST:event_stdidMouseEntered

    private void passwordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordMouseExited
        // TODO add your handling code here:
        jLabel2.setForeground(Color.black );
        password.setLocation(431, 93);
        
    }//GEN-LAST:event_passwordMouseExited

    private void passwordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordMouseEntered
        // TODO add your handling code here:
        jLabel2.setForeground(Color.red);
        password.setLocation(331, 93);
    }//GEN-LAST:event_passwordMouseEntered

    private void snameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_snameKeyTyped
        // TODO add your handling code here:
        
         
        
    }//GEN-LAST:event_snameKeyTyped

    private void snameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_snameKeyReleased
        // TODO add your handling code here:
      
      

    }//GEN-LAST:event_snameKeyReleased

    private void snameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_snameKeyPressed
        // TODO add your handling code here:

       char c = evt.getKeyChar();
        if(Character.isDigit(c)||Character.isWhitespace(c)||Character.isISOControl(c)||evt.isActionKey())
        {
            sname.setEditable(false);
   
        }
        else
        {
             
                sname.setEditable(true);
        }

        

     
    }//GEN-LAST:event_snameKeyPressed

    private void snameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_snameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_snameActionPerformed

    private void snameInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_snameInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_snameInputMethodTextChanged

    private void snameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_snameMouseExited
        // TODO add your handling code here:
        jLabel1.setForeground(Color.black);
        sname.setLocation(431, 45);
    }//GEN-LAST:event_snameMouseExited

    private void snameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_snameMouseEntered
        // TODO add your handling code here:

        jLabel1.setForeground(Color.red);
        sname.setLocation(331, 45);
    }//GEN-LAST:event_snameMouseEntered

    private void snameMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_snameMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_snameMouseMoved

    private void jLabel17MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel17MouseEntered

    private void jLabel16MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel16MouseEntered

    private void jLabel15MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel15MouseEntered

    private void jLabel13MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel13MouseEntered

    private void jLabel12MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel12MouseEntered

    private void jLabel11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel11MouseEntered

    private void jLabel10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel10MouseEntered

    private void jLabel9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel9MouseEntered

    private void jLabel8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel8MouseEntered

    private void jLabel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseEntered

    private void jLabel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseEntered

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseEntered

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseEntered

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseEntered

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
         if(jCheckBox1.isSelected())
        {
            password.setEchoChar((char)0);
        }
        else
        {
            password.setEchoChar('*');
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void dobMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dobMouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_dobMouseEntered

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void snameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_snameMouseClicked
        // TODO add your handling code here:
            

    }//GEN-LAST:event_snameMouseClicked

    private void stdidFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_stdidFocusGained
        // TODO add your handling code here:
       
    }//GEN-LAST:event_stdidFocusGained

    private void dobMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dobMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_dobMouseExited

    private void SECURQSMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SECURQSMouseEntered
        // TODO add your handling code here:
         SECURQS.setLocation(331, 760);
         jLabel18.setForeground(Color.red);
    }//GEN-LAST:event_SECURQSMouseEntered

    private void SECURQSMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SECURQSMouseExited
        // TODO add your handling code here:
         SECURQS.setLocation(431, 760);
                  jLabel18.setForeground(Color.BLUE);

    }//GEN-LAST:event_SECURQSMouseExited

    private void snameCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_snameCaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_snameCaretUpdate

    private void passwordCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_passwordCaretUpdate
        // TODO add your handling code here:

    }//GEN-LAST:event_passwordCaretUpdate

    private void snameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_snameFocusLost
        // TODO add your handling code here:
        
    }//GEN-LAST:event_snameFocusLost

    private void passwordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordKeyPressed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_passwordKeyPressed

    private void degaggFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_degaggFocusLost
        // TODO add your handling code here:
        
    }//GEN-LAST:event_degaggFocusLost

    private void pucpercMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pucpercMouseClicked
        // TODO add your handling code here:
    
    }//GEN-LAST:event_pucpercMouseClicked

    private void degpassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_degpassFocusLost
        // TODO add your handling code here:
        
    }//GEN-LAST:event_degpassFocusLost

    private void SECURQSKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SECURQSKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(Character.isLetter(c)||Character.isWhitespace(c)||Character.isISOControl(c)||evt.isActionKey())
        {
                SECURQS.setEditable(true);
                
        }
       
        else
        {
            SECURQS.setEditable(false);
         
        }
    }//GEN-LAST:event_SECURQSKeyPressed

    private void degaggMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_degaggMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_degaggMouseClicked

    private void passwordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordMouseClicked

    private void mnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mnameFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_mnameFocusGained

    
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame6().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField SECURQS;
    private javax.swing.JLabel STDVAL;
    private javax.swing.JTextField backlogs;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField clname;
    private javax.swing.JTextField degagg;
    private javax.swing.JTextField degpass;
    private com.toedter.calendar.JDateChooser dob;
    private javax.swing.JTextField email;
    private javax.swing.JTextField fname;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField mname;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField pucpass;
    private javax.swing.JTextField pucperc;
    private java.awt.Scrollbar scrollbar1;
    private javax.swing.JTextField sname;
    private javax.swing.JTextField sslcpass;
    private javax.swing.JTextField sslcperc;
    private javax.swing.JTextField stdid;
    // End of variables declaration//GEN-END:variables
}
