/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication3;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class QST extends javax.swing.JFrame {

    /**
     * Creates new form QST
     */
    public QST() {
        initComponents();

        jButton3.setVisible(false);
        jButton2.setVisible(false);

    }
    public QST(String uname,String COM, String TestN,int NM1,int NM2,int PG,int i,int a,int b)
    {
        initComponents();
        Comp_ID.setText(COM);
        Test_Name.setText(TestN);
        Test_ID.setText(uname);
        NO1.setText(""+NM1);
        NO2.setText(""+NM2);
        PGNO.setText(""+PG);

        QN1.setText(""+i);
        jButton2.setVisible(false);
        jButton3.setVisible(true);
        jButton1.setVisible(false);
        jComboBox1.setSelectedIndex(a);
        jComboBox2.setSelectedIndex(b);
        jComboBox1.setEnabled(false);
        jComboBox2.setEnabled(false);
        Comp_ID.setEnabled(false);
        Test_Name.setEnabled(false);
        Test_ID.setEnabled(false);

       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Comp_ID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Test_ID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Test_Name = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        NO1 = new javax.swing.JTextField();
        NO2 = new javax.swing.JTextField();
        PGNO = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        QN1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TextArea1 = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        OPA1 = new javax.swing.JTextField();
        OPB1 = new javax.swing.JTextField();
        OPD1 = new javax.swing.JTextField();
        OPC1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        ANA1 = new javax.swing.JRadioButton();
        ANB1 = new javax.swing.JRadioButton();
        ANC1 = new javax.swing.JRadioButton();
        AND1 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton4 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 0));
        jLabel1.setText("Practice Aptitude Test");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(441, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(605, 605, 605))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        Comp_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Comp_IDActionPerformed(evt);
            }
        });

        jLabel2.setText("Company ID");

        jLabel3.setText("Test ID");

        jLabel4.setText("Test Name");

        NO1.setEditable(false);
        NO1.setBackground(new java.awt.Color(204, 204, 255));
        NO1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        NO1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NO1.setText("1");
        NO1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NO1ActionPerformed(evt);
            }
        });

        NO2.setEditable(false);
        NO2.setBackground(new java.awt.Color(204, 204, 255));
        NO2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        NO2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NO2.setText("25");
        NO2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NO2ActionPerformed(evt);
            }
        });

        PGNO.setEditable(false);
        PGNO.setBackground(new java.awt.Color(204, 204, 255));
        PGNO.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PGNO.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PGNO.setText("1");

        jLabel5.setText("Page NO");

        jLabel6.setText("TO");

        jLabel7.setText("QUESTIONS");

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        QN1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        QN1.setForeground(new java.awt.Color(255, 0, 0));
        QN1.setText("1");
        jPanel4.add(QN1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 20));

        TextArea1.setColumns(20);
        TextArea1.setRows(5);
        TextArea1.setBorder(javax.swing.BorderFactory.createTitledBorder("Question"));
        jScrollPane3.setViewportView(TextArea1);

        jPanel4.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 706, 386));

        jLabel9.setText("A.");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 425, -1, -1));

        jLabel10.setText("B.");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 425, -1, -1));

        jLabel11.setText("C.");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(516, 425, 22, -1));

        jLabel12.setText("D.");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(755, 425, 21, -1));
        jPanel4.add(OPA1, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 418, 199, 28));
        jPanel4.add(OPB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 418, 187, 28));
        jPanel4.add(OPD1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 418, 153, 28));
        jPanel4.add(OPC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(556, 418, 195, 28));

        jLabel13.setBackground(new java.awt.Color(204, 255, 255));
        jLabel13.setText("SET ANSWER");
        jLabel13.setOpaque(true);
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(784, 41, 104, 23));

        buttonGroup1.add(ANA1);
        ANA1.setText("A");
        jPanel4.add(ANA1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 80, 60, -1));

        buttonGroup1.add(ANB1);
        ANB1.setText("B");
        jPanel4.add(ANB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 110, 60, -1));

        buttonGroup1.add(ANC1);
        ANC1.setText("C");
        jPanel4.add(ANC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 140, 60, -1));

        buttonGroup1.add(AND1);
        AND1.setText("D");
        jPanel4.add(AND1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 170, 60, -1));

        jButton1.setText("SUBMIT QUESTION");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 464, 190, -1));

        jButton2.setText(">> ADD QUESTION");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(491, 464, -1, -1));

        jButton3.setText("SUBMIT QUESTION");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, 180, -1));

        jTextArea1.setBackground(new java.awt.Color(204, 204, 204));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Add Explanation", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        jScrollPane2.setViewportView(jTextArea1);

        jButton4.setBackground(new java.awt.Color(153, 255, 153));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setText("SUBMIT TEST");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(204, 255, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Select Time"));

        jLabel14.setText("MINUTES :");

        jLabel8.setText("HOUR :");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addGap(71, 71, 71))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Comp_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(Test_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(Test_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(NO1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(NO2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 946, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(103, 103, 103))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(PGNO, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(39, 39, 39))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(27, 27, 27)))
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(42, 42, 42))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PGNO, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Comp_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Test_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(Test_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(NO1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(NO2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 625, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Comp_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Comp_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Comp_IDActionPerformed

    private void NO1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NO1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NO1ActionPerformed

    private void NO2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NO2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NO2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(Comp_ID.getText().equals(""))
             {
              JOptionPane.showMessageDialog(null,"Please enter company ID");   
             }
        else if(Test_ID.getText().equals(""))
         {
             JOptionPane.showMessageDialog(null,"Please enter test ID");   
             
         }
        else if( Test_Name.getText().equals(""))
         {
             JOptionPane.showMessageDialog(null,"Please enter test name");   
             
         }
         else if(TextArea1.getText().equals(""))
         {
             JOptionPane.showMessageDialog(null,"Please enter question");   
             
         }
        else if(OPA1.getText().equals("")||OPB1.getText().equals("")||OPC1.getText().equals("")||OPD1.getText().equals(""))
         {
             JOptionPane.showMessageDialog(null,"Please enter option");   
             
         }
         else if(jComboBox1.getSelectedItem().equals("0" )&&jComboBox2.getSelectedItem().equals("0" ))
         {
             JOptionPane.showMessageDialog(null,"Please select time");   
             
         }
        
        else
         {  
        try
                {

                    Class.forName("com.mysql.jdbc.Driver");
                    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/student","root","");
                    String sql,sql1,sql2,sql3,sql4;
                    PreparedStatement pst,pst1,pst2,pst3,pst4;
                    
                    sql1="SELECT * FROM `criteria` where comp_ID = ? LIMIT 0 , 30";
                    pst1 = con.prepareStatement(sql1);
                    pst1.setString(1,Comp_ID.getText());
                    ResultSet rs1=pst1.executeQuery();
                    if(rs1.next())
                    {  
                        sql2="SELECT * FROM `APTTEST` where Test_ID  = ? LIMIT 0 , 30";
                        pst2 = con.prepareStatement(sql2);
                        pst2.setString(1,Test_ID.getText());
                        ResultSet rs2=pst2.executeQuery();
                        if(!(rs2.next()))
                        {
                                                    sql = "INSERT INTO `student`.`APTTEST` (`Comp_ID`,`Test_ID`,`Test_name`,`QNO`,`Question`,`OPA`,`OPB`,`OPC`,`OPD`,`Answer`,`PGNO`,`EXPL`,`HR`,`MN`)VALUES(?,?,?,?,?,?,?, ?, ?, ?, ?, ?, ?, ?)";
                                                    pst = con.prepareStatement(sql);
                                                    pst.setString(1, Comp_ID.getText());
                                                    pst.setString(2, Test_ID.getText());
                                                    pst.setString(3, Test_Name.getText());
                                                    pst.setString(4, NO1.getText());
                                                    int PG = Integer.parseInt(PGNO.getText());
                                                    pst.setInt(11, PG);
                                                    pst.setString(12, jTextArea1.getText());
                                                                                                   
                                                           pst.setString(5,TextArea1.getText());
                                                           pst.setString(6,OPA1.getText());
                                                           pst.setString(7,OPB1.getText());
                                                           pst.setString(8,OPC1.getText());
                                                           pst.setString(9,OPD1.getText());
                                                          if(ANA1.isSelected())
                                                          {
                                                              pst.setString(10,ANA1.getText());

                                                          }
                                                          if(ANB1.isSelected())
                                                          {
                                                              pst.setString(10,ANB1.getText());

                                                          }
                                                          if(ANC1.isSelected())
                                                          {
                                                              pst.setString(10,ANC1.getText());

                                                          }
                                                          if(AND1.isSelected())
                                                          {
                                                              pst.setString(10,AND1.getText());

                                                          }
                                                           int i=jComboBox1.getSelectedIndex();
                                                           pst.setString(13,jComboBox1.getItemAt(i));
                                                            int j=jComboBox2.getSelectedIndex();
                                                           pst.setString(14,jComboBox2.getItemAt(j));
                                                           

                                                       pst.execute();
                                                        JOptionPane.showMessageDialog(null,"Question submitted");
                                                        jButton1.setVisible(false);
                                                        jButton2.setVisible(true);
                                                      
                        }
                        else
                        {
                                JOptionPane.showMessageDialog(null," This ID already used please enter another ID");
                                Test_ID.setText("");
                        }
                    }
                    else
                    {
                          JOptionPane.showMessageDialog(null,"Company ID not found");
                          Comp_ID.setText("");
                    }

                }
                catch(HeadlessException | ClassNotFoundException | SQLException e )
                {
                    JOptionPane.showMessageDialog(null,e);
                }
       }  
     
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
        int i = Integer.parseInt(QN1.getText());
        i++;
         String usern = Test_ID.getText();
        String comp = Comp_ID.getText();
        String TestName = Test_Name.getText();
        int m =Integer.parseInt(NO1.getText());
        int n =Integer.parseInt(NO2.getText());
        int PG = Integer.parseInt(PGNO.getText());
        int a = jComboBox1.getSelectedIndex();
        int b = jComboBox2.getSelectedIndex();
       if(m==n)
       {
           m = 1;
           n = 25;
           PG = PG + 1;
       }
        else
       {
                  m = m +1;
 
       }
        
        
         new QST(usern,comp,TestName,m,n,PG,i,a,b).setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if(Comp_ID.getText().equals(""))
             {
              JOptionPane.showMessageDialog(null,"Please enter company ID");   
             }
        else if(Test_ID.getText().equals(""))
         {
             JOptionPane.showMessageDialog(null,"Please enter test ID");   
             
         }
        else if( Test_Name.getText().equals(""))
         {
             JOptionPane.showMessageDialog(null,"Please enter test name");   
             
         }
        else if(TextArea1.getText().equals(""))
         {
             JOptionPane.showMessageDialog(null,"Please enter question");   
             
         }
        else if(OPA1.getText().equals("")||OPB1.getText().equals("")||OPC1.getText().equals("")||OPD1.getText().equals(""))
         {
             JOptionPane.showMessageDialog(null,"Please enter option");   
             
         }
        else if(jComboBox1.getSelectedItem().equals("0" )&&jComboBox2.getSelectedItem().equals("0" ))
         {
             JOptionPane.showMessageDialog(null,"Please select time");   
             
         }
         else
         {  
         try
                {

                    Class.forName("com.mysql.jdbc.Driver");
                    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/student","root","");
                    String sql,sql1,sql2,sql3,sql4;
                    PreparedStatement pst,pst1,pst2,pst3,pst4;
                                                    sql = "INSERT INTO `student`.`APTTEST` (`Comp_ID`,`Test_ID`,`Test_name`,`QNO`,`Question`,`OPA`,`OPB`,`OPC`,`OPD`,`Answer`,`PGNO`,`EXPL`,`HR`,`MN`)VALUES(?,?,?,?,?,?,?, ?, ?, ?, ?, ?, ?, ?)";
                                                    pst = con.prepareStatement(sql);
                                                    pst.setString(1, Comp_ID.getText());
                                                    pst.setString(2, Test_ID.getText());
                                                    pst.setString(3, Test_Name.getText());
                                                    pst.setString(4, NO1.getText());
                                                    int PG = Integer.parseInt(PGNO.getText());
                                                    pst.setInt(11, PG);
                                                    pst.setString(12, jTextArea1.getText());
                                                                                                   
                                                           pst.setString(5,TextArea1.getText());
                                                           pst.setString(6,OPA1.getText());
                                                           pst.setString(7,OPB1.getText());
                                                           pst.setString(8,OPC1.getText());
                                                           pst.setString(9,OPD1.getText());
                                                          if(ANA1.isSelected())
                                                          {
                                                              pst.setString(10,ANA1.getText());

                                                          }
                                                          if(ANB1.isSelected())
                                                          {
                                                              pst.setString(10,ANB1.getText());

                                                          }
                                                          if(ANC1.isSelected())
                                                          {
                                                              pst.setString(10,ANC1.getText());

                                                          }
                                                          if(AND1.isSelected())
                                                          {
                                                              pst.setString(10,AND1.getText());

                                                          }
                                                          int i=jComboBox1.getSelectedIndex();
                                                           pst.setString(13,jComboBox1.getItemAt(i));
                                                            int j=jComboBox2.getSelectedIndex();
                                                           pst.setString(14,jComboBox2.getItemAt(j));
                                                           
                                                       pst.execute();
                                                        JOptionPane.showMessageDialog(null,"Question submitted");
                                                                jButton3.setEnabled(false);
                                                                jButton2.setVisible(true);

                       }
                catch(HeadlessException | ClassNotFoundException | SQLException e )
                {
                    JOptionPane.showMessageDialog(null,e);
                }    
          }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QST.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QST.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QST.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QST.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QST().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton ANA1;
    private javax.swing.JRadioButton ANB1;
    private javax.swing.JRadioButton ANC1;
    private javax.swing.JRadioButton AND1;
    private javax.swing.JTextField Comp_ID;
    private javax.swing.JTextField NO1;
    private javax.swing.JTextField NO2;
    private javax.swing.JTextField OPA1;
    private javax.swing.JTextField OPB1;
    private javax.swing.JTextField OPC1;
    private javax.swing.JTextField OPD1;
    private javax.swing.JTextField PGNO;
    private javax.swing.JLabel QN1;
    private javax.swing.JTextField Test_ID;
    private javax.swing.JTextField Test_Name;
    private javax.swing.JTextArea TextArea1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
